import {
  pgTable,
  uuid,
  varchar,
  text,
  timestamp,
  boolean,
  integer,
  real,
  jsonb,
  pgEnum,
  index,
  unique,
  uniqueIndex,
  type AnyPgColumn,
} from "drizzle-orm/pg-core";
import { relations, sql } from "drizzle-orm";

// ─── Enums ───────────────────────────────────────────────────────────────────

export const crawlStatusEnum = pgEnum("crawl_status", [
  "pending",
  "running",
  "completed",
  "failed",
  "cancelled",
]);

export const severityEnum = pgEnum("severity", [
  "critical",
  "high",
  "medium",
  "low",
  "info",
]);

export const issueCategoryEnum = pgEnum("issue_category", [
  "technical",
  "on_page",
  "performance",
  "schema",
  "content",
  "entity",
  "geo",
  "aeo",
  "eeat",
  "llm",
  "citation",
  "accessibility",
  "security",
]);

export const issueStatusEnum = pgEnum("issue_status", [
  "open",
  "fixed",
  "ignored",
  "wont_fix",
]);

export const linkTypeEnum = pgEnum("link_type", ["internal", "external"]);

export const llmsFileKindEnum = pgEnum("llms_file_kind", ["llms_txt", "llms_full_txt"]);

/**
 * Phase 37 — where a stored site-level file row came from. `discovered` rows
 * are written by a crawl and are regenerated by the next one (so they are NOT
 * user-deletable); `manual` rows are added by a user through the UI, carry no
 * crawl run, and survive crawls until the user removes them.
 */
export const siteFileSourceEnum = pgEnum("site_file_source", ["discovered", "manual"]);

/**
 * Phase 37 — an XML sitemap is a machine-readable index this platform fetches
 * and parses; an HTML sitemap is a human-readable page and is deliberately
 * recorded as a link only (never fetched), so `raw_content` stays NULL for it
 * by design rather than by failure.
 */
export const sitemapDocKindEnum = pgEnum("sitemap_doc_kind", ["xml", "html"]);

export const userStatusEnum = pgEnum("user_status", [
  "active",
  "suspended",
  "deleted",
]);

// Section 11 (V2): fixed initial action set for the RBAC permission matrix.
// A central registry (features table) keeps *what* is protected dynamic;
// this enum keeps *how* (the verbs) fixed per V2 section 11's explicit list,
// while still leaving room to add a new enum value later without a rewrite.
export const permissionActionEnum = pgEnum("permission_action", [
  "view",
  "create",
  "edit",
  "delete",
  "export",
]);

// Phase 16: dynamic subscription packages (read-v2.md §11).
export const packageStatusEnum = pgEnum("package_status", ["active", "inactive"]);

export const billingPeriodEnum = pgEnum("billing_period", [
  "monthly",
  "yearly",
  "one_time",
]);

// Phase 17: Limitations / Usage (read.md §12/§13). Matches the period
// concept named across §12's "Set Period" step and the Access Decision Flow
// (§14) — day/week/month for recurring quotas, "lifetime" for a one-time,
// never-resets cap (e.g. total websites ever created on a package with no
// recurring reset).
export const limitPeriodEnum = pgEnum("limit_period", ["day", "week", "month", "lifetime"]);

// ─── Users ───────────────────────────────────────────────────────────────────

export const users = pgTable(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name", { length: 255 }).notNull(),
    email: varchar("email", { length: 255 }).notNull().unique(),
    passwordHash: text("password_hash").notNull(),
    emailVerified: boolean("email_verified").default(false).notNull(),
    emailVerifiedAt: timestamp("email_verified_at"),
    status: userStatusEnum("status").default("active").notNull(),
    // Phase 14 stub, DEPRECATED as of Phase 16 — superseded by
    // `subscriptionPackageId` below (a real FK into `packages`). Left in
    // place (nullable, unused by any write path from Phase 16 onward) only
    // so historical data isn't silently discarded; no code reads it for
    // authoritative decisions anymore.
    subscriptionPackage: varchar("subscription_package", { length: 100 }),
    // Phase 16: the real, dynamic subscription-package pointer. Nullable —
    // a user with no package assigned is a valid, common state (e.g. brand
    // new signups before an admin assigns one). `onDelete: "set null"` so
    // deactivating/removing a package's *row* (which Phase 16 never does —
    // deactivate only flips `status`) can never cascade-delete a user; this
    // is just defensive in case a package is ever hard-deleted by a future
    // admin/db operation.
    subscriptionPackageId: uuid("subscription_package_id").references(() => packages.id, {
      onDelete: "set null",
    }),
    // User Dashboard & Account Self-Service addition (2026-08-23): simple
    // E.164-ish phone field, zod-validated at the API layer — no SMS/OTP
    // verification, out of scope per the spec. Nullable — most existing
    // users have none.
    phone: varchar("phone", { length: 32 }),
    // Structured address, explicitly framed in the UI as "can be used as
    // billing address" but with NO billing/invoicing logic attached in this
    // pass — just stored fields.
    addressLine1: varchar("address_line1", { length: 255 }),
    addressLine2: varchar("address_line2", { length: 255 }),
    city: varchar("city", { length: 120 }),
    state: varchar("state", { length: 120 }),
    postalCode: varchar("postal_code", { length: 32 }),
    addressCountry: varchar("address_country", { length: 2 }),
    // Stage 3 (2026-08-23): pending-email-change state machine. A user's
    // `email` column (the active login credential) is NEVER overwritten
    // until the OTP sent to the NEW address is confirmed — this prevents a
    // user from locking themselves out by fat-fingering an email they don't
    // control. Mirrors the exact hash/expiry shape `emailVerificationTokens`
    // already uses (`hashOtp`/`getOtpExpiry` from `src/lib/auth/otp.ts`),
    // just inlined on `users` instead of a separate table since there is at
    // most one pending change per user at a time (no history needed).
    pendingEmail: varchar("pending_email", { length: 255 }),
    pendingEmailOtpHash: text("pending_email_otp_hash"),
    pendingEmailOtpExpiresAt: timestamp("pending_email_otp_expires_at"),
    pendingEmailOtpAttempts: integer("pending_email_otp_attempts").default(0).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [index("users_email_idx").on(t.email)]
);

// ─── Email Verification Tokens (OTP) ─────────────────────────────────────────

export const emailVerificationTokens = pgTable(
  "email_verification_tokens",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    attempts: integer("attempts").default(0).notNull(),
    usedAt: timestamp("used_at"),
    invalidatedAt: timestamp("invalidated_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("evt_user_id_idx").on(t.userId)]
);

// ─── Password Reset Tokens ────────────────────────────────────────────────────

export const passwordResetTokens = pgTable(
  "password_reset_tokens",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull().unique(),
    expiresAt: timestamp("expires_at").notNull(),
    usedAt: timestamp("used_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("prt_user_id_idx").on(t.userId)]
);

// ─── Sessions ─────────────────────────────────────────────────────────────────

export const sessions = pgTable(
  "sessions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    sessionIdentifier: varchar("session_identifier", { length: 128 })
      .notNull()
      .unique(),
    expiresAt: timestamp("expires_at").notNull(),
    revokedAt: timestamp("revoked_at"),
    lastUsedAt: timestamp("last_used_at").defaultNow().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("sessions_user_id_idx").on(t.userId),
    index("sessions_identifier_idx").on(t.sessionIdentifier),
  ]
);

// ─── Rate Limit Records ───────────────────────────────────────────────────────

export const rateLimitRecords = pgTable(
  "rate_limit_records",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key", { length: 512 }).notNull(),
    action: varchar("action", { length: 64 }).notNull(),
    attempts: integer("attempts").default(1).notNull(),
    windowStart: timestamp("window_start").defaultNow().notNull(),
    blockedUntil: timestamp("blocked_until"),
  },
  (t) => [index("rl_key_action_idx").on(t.key, t.action)]
);

// ─── Websites ─────────────────────────────────────────────────────────────────

export const websites = pgTable(
  "websites",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: varchar("name", { length: 255 }).notNull(),
    domain: varchar("domain", { length: 255 }).notNull(),
    url: text("url").notNull(),
    country: varchar("country", { length: 10 }),
    // Crawl configuration (Phase 6 crawler will read these; no crawling happens yet).
    maxPages: integer("max_pages").default(100).notNull(),
    maxDepth: integer("max_depth").default(3).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
    // Phase 28 — Competitor / Content Gap: a competitor entry is modeled as
    // another row in THIS table (not a parallel table) specifically so it
    // can flow through the entire existing crawl pipeline (run-crawl.ts),
    // scoring (Phase 22), and recommendation-aggregation (Phase 23) logic
    // verbatim — all of which already operate purely in terms of a
    // `websites.id` / `url` / `maxPages` / `maxDepth` row. `isCompetitor`
    // discriminates it from the user's own owned properties;
    // `competitorForWebsiteId` links it back to the owned site it's being
    // compared against. Every listing query the user's website
    // list/switcher uses (`listUserWebsites`, `GET /api/websites`) filters
    // `isCompetitor = false` so a competitor entry never appears as if it
    // were one of the user's own sites, and — per the Phase 17 "Maximum
    // Websites" package limit being scoped to the user's own properties,
    // not comparison targets — competitor rows are excluded from any count
    // that limit would apply to (see read.md Phase 28 write-up).
    isCompetitor: boolean("is_competitor").default(false).notNull(),
    competitorForWebsiteId: uuid("competitor_for_website_id").references((): AnyPgColumn => websites.id, {
      onDelete: "cascade",
    }),
  },
  (t) => [
    index("websites_user_id_idx").on(t.userId),
    unique("websites_user_domain_unique").on(t.userId, t.domain),
    index("websites_competitor_for_website_id_idx").on(t.competitorForWebsiteId),
  ]
);

// ─── Crawl Runs ──────────────────────────────────────────────────────────────

export const crawlRuns = pgTable(
  "crawl_runs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    status: crawlStatusEnum("status").default("pending").notNull(),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    pagesDiscovered: integer("pages_discovered").default(0),
    pagesCrawled: integer("pages_crawled").default(0),
    errors: jsonb("errors").$type<string[]>().default([]),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    // At most one pending/running crawl per website — enforced at the DB
    // level (not just app-level check-then-insert) to close the race where
    // two "start crawl" requests land concurrently.
    uniqueIndex("crawl_runs_one_active_per_website")
      .on(t.websiteId)
      .where(sql`${t.status} IN ('pending', 'running')`),
    // Phase 33 — Performance Optimization: `computeWebsiteScores`/
    // `computeWebsiteRecommendations`/`computeWebsiteAiSearch`/
    // `computeWebsiteEeat`/report assembly (Phases 22/23/24/25/30) all run
    // `WHERE website_id = ? AND status = 'completed' ORDER BY created_at DESC
    // LIMIT 1` to find a website's latest completed crawl — a genuinely
    // common, hot query with no supporting index before this phase (the
    // unique index above only covers the pending/running partial case).
    // See read.md's Phase 33 write-up for the `EXPLAIN ANALYZE` before/after.
    index("crawl_runs_website_status_created_idx").on(t.websiteId, t.status, t.createdAt),
  ]
);

// ─── Pages ───────────────────────────────────────────────────────────────────

export const pages = pgTable(
  "pages",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    crawlRunId: uuid("crawl_run_id")
      .notNull()
      .references(() => crawlRuns.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    statusCode: integer("status_code"),
    contentType: varchar("content_type", { length: 255 }),
    title: text("title"),
    metaDescription: text("meta_description"),
    canonical: text("canonical"),
    robots: text("robots"),
    h1: text("h1"),
    wordCount: integer("word_count"),
    responseTime: integer("response_time"),
    pageSize: integer("page_size"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    // Phase 24 — AI Search Intelligence: deterministic content-structure
    // signals extracted once per page during the same crawl pass (no second
    // fetch), feeding GEO/AEO readiness dimensions (Headings/Lists/Tables/FAQ
    // Structures/Question Coverage/Content Chunkability). `headingsJson`
    // duplicates what `extractHeadings()` already computes per-crawl (Phase 7
    // only ever persisted the single H1 text) — persisting the full H1-H6
    // array here is what lets readiness be recomputed live later without
    // re-crawling, same "raw + parsed, persisted once" precedent as
    // `schemas.rawJson` (Phase 11) and `llmsFiles.sections` (Phase 18).
    headingsJson: jsonb("headings_json").$type<{ level: number; text: string }[]>(),
    listCount: integer("list_count"),
    orderedListCount: integer("ordered_list_count"),
    unorderedListCount: integer("unordered_list_count"),
    tableCount: integer("table_count"),
    definitionListCount: integer("definition_list_count"),
    questionHeadingCount: integer("question_heading_count"),
    hasFaqHeading: boolean("has_faq_heading"),
    // Phase 25 — E-E-A-T / Trust: observable authorship/date markup signals,
    // extracted once per page during the same crawl pass (see
    // `extractEeatSignals` in extract.ts). Deliberately NOT re-storing
    // Organization/Person schema presence — that's Phase 24's job and is read
    // live from the existing `schemas` table.
    hasAuthorByline: boolean("has_author_byline"),
    hasRelAuthorLink: boolean("has_rel_author_link"),
    hasVisibleDate: boolean("has_visible_date"),
  },
  (t) => [
    // Phase 33 — Performance Optimization: `pages.crawlRunId` is the single
    // most-queried filter column in this whole schema — every per-crawl-run
    // page listing in Phases 22/23/24/25/30/31's compute functions filters
    // on it, and it had no index at all (only the implicit PK index on
    // `id`), meaning every one of those was a sequential scan over the
    // entire `pages` table once it grew past a trivial size. `websiteId` is
    // also FK'd but never queried alone in the hot paths above (always via
    // `crawlRunId` from a resolved latest-run) — included anyway since it's
    // a real FK with real ownership-check/listing queries
    // (`src/lib/websites/queries.ts`) that filter on it directly.
    index("pages_crawl_run_id_idx").on(t.crawlRunId),
    index("pages_website_id_idx").on(t.websiteId),
  ]
);

// ─── Page Metrics (Lighthouse) ───────────────────────────────────────────────

export const pageMetrics = pgTable(
  "page_metrics",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    pageId: uuid("page_id")
      .notNull()
      .references(() => pages.id, { onDelete: "cascade" }),
    fcp: real("fcp"),
    lcp: real("lcp"),
    cls: real("cls"),
    inp: real("inp"),
    tbt: real("tbt"),
    speedIndex: real("speed_index"),
    performanceScore: integer("performance_score"),
    accessibilityScore: integer("accessibility_score"),
    bestPracticesScore: integer("best_practices_score"),
    seoScore: integer("seo_score"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("page_metrics_page_id_idx").on(t.pageId)]
);

// ─── Images ──────────────────────────────────────────────────────────────────

export const images = pgTable(
  "images",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    pageId: uuid("page_id")
      .notNull()
      .references(() => pages.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    alt: text("alt"),
    width: integer("width"),
    height: integer("height"),
    size: integer("size"),
    format: varchar("format", { length: 20 }),
    lazyLoaded: boolean("lazy_loaded").default(false),
    isLcp: boolean("is_lcp").default(false),
  },
  (t) => [index("images_page_id_idx").on(t.pageId)]
);

// ─── Links ───────────────────────────────────────────────────────────────────

export const links = pgTable(
  "links",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    pageId: uuid("page_id")
      .notNull()
      .references(() => pages.id, { onDelete: "cascade" }),
    targetUrl: text("target_url").notNull(),
    anchorText: text("anchor_text"),
    linkType: linkTypeEnum("link_type").notNull(),
    statusCode: integer("status_code"),
    isInternal: boolean("is_internal").default(true),
    isBroken: boolean("is_broken").default(false),
  },
  (t) => [index("links_page_id_idx").on(t.pageId)]
);

// ─── Schemas ─────────────────────────────────────────────────────────────────

export const schemas = pgTable(
  "schemas",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    pageId: uuid("page_id")
      .notNull()
      .references(() => pages.id, { onDelete: "cascade" }),
    schemaType: varchar("schema_type", { length: 255 }),
    rawJson: jsonb("raw_json"),
    isValid: boolean("is_valid").default(false),
    errors: jsonb("errors").$type<string[]>().default([]),
    warnings: jsonb("warnings").$type<string[]>().default([]),
  },
  (t) => [index("schemas_page_id_idx").on(t.pageId)]
);

// ─── llms.txt / llms-full.txt (Phase 18) ──────────────────────────────────────
//
// Site-level (like robots.txt/sitemap.xml), not per-page — one row per file
// per crawl run, holding both the raw fetched content and the parsed
// structure, following the same "raw + parsed, persisted once per crawl"
// shape schemas.rawJson (Phase 11) and sitemap documents (Phase 12) use.

export const llmsFiles = pgTable("llms_files", {
  id: uuid("id").defaultRandom().primaryKey(),
  websiteId: uuid("website_id")
    .notNull()
    .references(() => websites.id, { onDelete: "cascade" }),
  // Phase 37 made this NULLABLE: a manually-added llms.txt belongs to the
  // website, not to any crawl run. Crawl-written rows still always carry one.
  crawlRunId: uuid("crawl_run_id").references(() => crawlRuns.id, { onDelete: "cascade" }),
  kind: llmsFileKindEnum("kind").notNull(),
  url: text("url").notNull(),
  found: boolean("found").default(false).notNull(),
  httpStatus: integer("http_status"),
  rawContent: text("raw_content"),
  sizeBytes: integer("size_bytes"),
  title: text("title"),
  summary: text("summary"),
  sections: jsonb("sections").$type<{ heading: string; links: { title: string; url: string; description: string | null; isValidUrl: boolean }[] }[]>(),
  // Phase 37 additions — see `siteFileSourceEnum` and `sitemapDocuments` below.
  source: siteFileSourceEnum("source").default("discovered").notNull(),
  truncated: boolean("truncated").default(false).notNull(),
  fetchError: text("fetch_error"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ─── Site-level file CONTENT: sitemaps + robots.txt (Phase 37) ───────────────
//
// Before Phase 37 the sitemap and robots.txt fetches happened inside the
// crawl, were handed to the rule engine, and were then DISCARDED — only the
// resulting `seo_issues` rows survived. That meant the Sitemap and Robots.txt
// reports could say "a sitemap was found" but could never show WHICH file, how
// many URLs it listed, or what it actually said. These two tables close that
// gap by persisting exactly what `llms_files` (Phase 18) already persisted for
// llms.txt: the fetch outcome plus the raw body, once per crawl run.
//
// A `manual` row (see `siteFileSourceEnum`) carries a NULL `crawl_run_id` — it
// is user-supplied, not crawl-derived, and is the only kind a user may delete.

export const sitemapDocuments = pgTable(
  "sitemap_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    crawlRunId: uuid("crawl_run_id").references(() => crawlRuns.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    kind: sitemapDocKindEnum("kind").notNull(),
    source: siteFileSourceEnum("source").default("discovered").notNull(),
    found: boolean("found").default(false).notNull(),
    httpStatus: integer("http_status"),
    /**
     * NULL for `kind = 'html'` ALWAYS — an HTML sitemap is a human-readable
     * page, not a machine-readable index, so this platform deliberately never
     * fetches its body. NULL therefore means "not fetched by design" for HTML
     * and "fetch produced no body" for XML; `fetchError`/`found` disambiguate.
     */
    rawContent: text("raw_content"),
    sizeBytes: integer("size_bytes"),
    /** Parsed `<url>` entries (urlset) or `<sitemap>` entries (index). NULL = not parsed. */
    urlCount: integer("url_count"),
    /** True when the document parsed as a `<sitemapindex>` rather than a `<urlset>`. */
    isIndex: boolean("is_index"),
    /**
     * The response exceeded `safeFetch`'s byte cap. `safeFetch` aborts rather
     * than returning a partial body, so a truncated row stores NO content —
     * the flag exists so the UI can say "too large to store" instead of
     * presenting an incomplete file as if it were whole.
     */
    truncated: boolean("truncated").default(false).notNull(),
    /** Verbatim reason a fetch did not produce a body (blocked address, timeout, size cap…). */
    fetchError: text("fetch_error"),
    fetchedAt: timestamp("fetched_at").defaultNow().notNull(),
  },
  (t) => [
    index("sitemap_documents_website_id_idx").on(t.websiteId),
    index("sitemap_documents_crawl_run_id_idx").on(t.crawlRunId),
  ]
);

export const robotsFiles = pgTable(
  "robots_files",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    crawlRunId: uuid("crawl_run_id").references(() => crawlRuns.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    source: siteFileSourceEnum("source").default("discovered").notNull(),
    found: boolean("found").default(false).notNull(),
    httpStatus: integer("http_status"),
    rawContent: text("raw_content"),
    sizeBytes: integer("size_bytes"),
    truncated: boolean("truncated").default(false).notNull(),
    fetchError: text("fetch_error"),
    fetchedAt: timestamp("fetched_at").defaultNow().notNull(),
  },
  (t) => [
    index("robots_files_website_id_idx").on(t.websiteId),
    index("robots_files_crawl_run_id_idx").on(t.crawlRunId),
  ]
);

// ─── SEO Rules ───────────────────────────────────────────────────────────────

export const seoRules = pgTable("seo_rules", {
  id: uuid("id").defaultRandom().primaryKey(),
  ruleKey: varchar("rule_key", { length: 255 }).notNull().unique(),
  category: issueCategoryEnum("category").notNull(),
  severity: severityEnum("severity").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  recommendation: text("recommendation"),
  fixExample: text("fix_example"),
  impact: text("impact"),
  enabled: boolean("enabled").default(true).notNull(),
});

// ─── SEO Issues ──────────────────────────────────────────────────────────────

export const seoIssues = pgTable(
  "seo_issues",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    pageId: uuid("page_id")
      .notNull()
      .references(() => pages.id, { onDelete: "cascade" }),
    ruleId: uuid("rule_id")
      .notNull()
      .references(() => seoRules.id),
    category: issueCategoryEnum("category").notNull(),
    severity: severityEnum("severity").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    evidence: text("evidence"),
    status: issueStatusEnum("status").default("open").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    // Phase 33 — Performance Optimization: `pageId` is the column every
    // scoring/recommendation/report aggregation (`inArray(seoIssues.pageId,
    // pageIds)`, Phases 22/23/30) filters on — the single hottest lookup
    // column in this table, previously with no index at all. `ruleId` is
    // used by the recommendation-grouping join (Phase 23,
    // `innerJoin(seoRules, eq(seoIssues.ruleId, seoRules.id))`) — indexed so
    // that join doesn't degrade into a hash join over a full seq scan as
    // `seo_issues` grows.
    index("seo_issues_page_id_idx").on(t.pageId),
    index("seo_issues_rule_id_idx").on(t.ruleId),
  ]
);

// ─── Recommendations ─────────────────────────────────────────────────────────

export const recommendations = pgTable(
  "recommendations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    issueId: uuid("issue_id")
      .notNull()
      .references(() => seoIssues.id, { onDelete: "cascade" }),
    priority: integer("priority").default(50),
    recommendation: text("recommendation").notNull(),
    steps: jsonb("steps").$type<string[]>().default([]),
    expectedImpact: text("expected_impact"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("recommendations_issue_id_idx").on(t.issueId)]
);

// ─── PageSpeed / Lighthouse Audits (Phase 20) ─────────────────────────────────
//
// Deliberately a NEW, dedicated table rather than repurposing the
// pre-scaffolded `pageMetrics` table above: `pageMetrics` is keyed to a
// crawled `pages.id` row and has no status/strategy/error tracking, which
// doesn't fit a user-triggered, polled, mobile+desktop async job the way
// `crawlRuns` does for Phase 6's crawler. `pageMetrics` is left untouched
// (unused scaffold from Phase 2, not claimed by this phase).
//
// One row per (website, url, strategy). A single "Run PageSpeed Audit"
// click creates two rows sharing a `batchId` (mobile + desktop), matching
// the master doc's "Run: Mobile / Desktop" instruction (Section 31). The
// partial unique index mirrors `crawl_runs_one_active_per_website` (Phase 6)
// but scoped per strategy, so a mobile run and a desktop run can be
// in-flight at once without allowing two concurrent mobile runs.

export const pagespeedStrategyEnum = pgEnum("pagespeed_strategy", ["mobile", "desktop"]);

export const pagespeedAudits = pgTable(
  "pagespeed_audits",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    batchId: uuid("batch_id").notNull(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    url: text("url").notNull(),
    strategy: pagespeedStrategyEnum("strategy").notNull(),
    status: crawlStatusEnum("status").default("pending").notNull(),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    error: text("error"),
    // Lighthouse category scores, 0-100 (Lighthouse itself reports 0-1; stored as
    // whole percentages for direct display, same convention as pageMetrics above).
    performanceScore: integer("performance_score"),
    accessibilityScore: integer("accessibility_score"),
    bestPracticesScore: integer("best_practices_score"),
    seoScore: integer("seo_score"),
    // Core Web Vitals + supporting metrics, in their native Lighthouse units
    // (ms for time-based metrics, unitless for CLS).
    lcp: real("lcp"),
    cls: real("cls"),
    inp: real("inp"),
    fcp: real("fcp"),
    tbt: real("tbt"),
    speedIndex: real("speed_index"),
    ttfb: real("ttfb"),
    lighthouseVersion: varchar("lighthouse_version", { length: 20 }),
    // Trimmed Lighthouse result (categories + the headline audits only —
    // NOT the full raw LHR, which can run several MB per run with full
    // network/trace/screenshot data that Phase 20 has no use for).
    rawResult: jsonb("raw_result"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("pagespeed_audits_website_id_idx").on(t.websiteId),
    index("pagespeed_audits_batch_id_idx").on(t.batchId),
    uniqueIndex("pagespeed_audits_one_active_per_website_strategy")
      .on(t.websiteId, t.strategy)
      .where(sql`${t.status} IN ('pending', 'running')`),
  ]
);

export const pagespeedAuditsRelations = relations(pagespeedAudits, ({ one }) => ({
  website: one(websites, { fields: [pagespeedAudits.websiteId], references: [websites.id] }),
}));

// ─── RBAC: Features / Permissions / Roles (Phase 14/15, read-v2.md §11) ──────
//
// Feature -> Action -> Permission -> Role -> User, per read-v2.md §11.
// A central `features` registry means adding a future feature/action never
// requires touching this table shape again — only new rows.

export const features = pgTable(
  "features",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key", { length: 100 }).notNull().unique(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    sortOrder: integer("sort_order").default(0).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("features_key_idx").on(t.key)]
);

export const permissions = pgTable(
  "permissions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    featureId: uuid("feature_id")
      .notNull()
      .references(() => features.id, { onDelete: "cascade" }),
    action: permissionActionEnum("action").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [unique("permissions_feature_action_unique").on(t.featureId, t.action)]
);

export const roles = pgTable(
  "roles",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key", { length: 100 }).notNull().unique(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    // System roles (SUPER_ADMIN, USER) can't be deleted or renamed away from
    // their invariants by normal dashboard actions — read-v2.md §9: "No
    // normal dashboard action may remove these privileges from SUPER_ADMIN."
    isSystem: boolean("is_system").default(false).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [index("roles_key_idx").on(t.key)]
);

export const rolePermissions = pgTable(
  "role_permissions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    roleId: uuid("role_id")
      .notNull()
      .references(() => roles.id, { onDelete: "cascade" }),
    permissionId: uuid("permission_id")
      .notNull()
      .references(() => permissions.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    unique("role_permissions_role_permission_unique").on(t.roleId, t.permissionId),
    index("role_permissions_role_id_idx").on(t.roleId),
  ]
);

export const userRoles = pgTable(
  "user_roles",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    roleId: uuid("role_id")
      .notNull()
      .references(() => roles.id, { onDelete: "cascade" }),
    assignedAt: timestamp("assigned_at").defaultNow().notNull(),
  },
  (t) => [
    unique("user_roles_user_role_unique").on(t.userId, t.roleId),
    index("user_roles_user_id_idx").on(t.userId),
  ]
);

// ─── Subscription Packages (Phase 16, read-v2.md §11) ────────────────────────
//
// packages -> package_features (feature ON/OFF, reusing the *same*
// `features` table RBAC already seeds — see feature-catalog.ts's comment:
// "Feature availability must come from the same feature catalog used by
// RBAC"). Deliberately does NOT carry any numeric limit/quota data — that is
// Phase 17's `limit_definitions`/`package_limits` (a limit *value* + period
// is a different concern from a feature *toggle*, and conflating the two
// rows would make Phase 17 need to reshape this table rather than just add
// two new ones referencing `packages.id`).

export const packages = pgTable(
  "packages",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    // Stored as a plain float (matches this codebase's existing convention
    // for non-integer numeric columns, e.g. `pageMetrics.fcp`/`lcp`) rather
    // than a fixed-point `numeric` type, which isn't used anywhere else in
    // this schema yet. Zero paid APIs / no billing integration exists to
    // process this value — it's a display/plan-definition field only.
    price: real("price").default(0).notNull(),
    currency: varchar("currency", { length: 3 }).default("USD").notNull(),
    billingPeriod: billingPeriodEnum("billing_period").default("monthly").notNull(),
    // Deactivating a package flips this to "inactive" — it must NEVER be
    // deleted while users are still assigned to it (or at all, per the
    // Phase 16 spec: "Activate, Deactivate", not "Delete"). Users already
    // assigned to a since-deactivated package keep their `subscriptionPackageId`
    // pointer; entitlement enforcement (whether an inactive package's
    // features still work) is explicitly out of scope until Phase 17.
    status: packageStatusEnum("status").default("active").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [index("packages_status_idx").on(t.status)]
);

export const packageFeatures = pgTable(
  "package_features",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    packageId: uuid("package_id")
      .notNull()
      .references(() => packages.id, { onDelete: "cascade" }),
    featureId: uuid("feature_id")
      .notNull()
      .references(() => features.id, { onDelete: "cascade" }),
    enabled: boolean("enabled").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    unique("package_features_package_feature_unique").on(t.packageId, t.featureId),
    index("package_features_package_id_idx").on(t.packageId),
  ]
);

// ─── Package Upgrade Requests (User Dashboard & Account Self-Service, 2026-08-23) ─
//
// A deliberately lightweight request/approval workflow — NOT a payment flow.
// The user requests a different active package; a SUPER_ADMIN reviews and
// either approves (which calls the existing `setUserSubscriptionPackage`
// from Phase 16 to actually flip `users.subscriptionPackageId`) or rejects.
// No money changes hands anywhere in this table or its handlers.

export const packageUpgradeRequestStatusEnum = pgEnum("package_upgrade_request_status", [
  "pending",
  "approved",
  "rejected",
]);

export const packageUpgradeRequests = pgTable(
  "package_upgrade_requests",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    currentPackageId: uuid("current_package_id").references(() => packages.id, {
      onDelete: "set null",
    }),
    requestedPackageId: uuid("requested_package_id")
      .notNull()
      .references(() => packages.id, { onDelete: "cascade" }),
    status: packageUpgradeRequestStatusEnum("status").default("pending").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    resolvedAt: timestamp("resolved_at"),
    resolvedBy: uuid("resolved_by").references(() => users.id, { onDelete: "set null" }),
  },
  (t) => [
    index("package_upgrade_requests_user_id_idx").on(t.userId),
    index("package_upgrade_requests_status_idx").on(t.status),
  ]
);

export const packageUpgradeRequestsRelations = relations(packageUpgradeRequests, ({ one }) => ({
  user: one(users, { fields: [packageUpgradeRequests.userId], references: [users.id] }),
  currentPackage: one(packages, {
    fields: [packageUpgradeRequests.currentPackageId],
    references: [packages.id],
  }),
  requestedPackage: one(packages, {
    fields: [packageUpgradeRequests.requestedPackageId],
    references: [packages.id],
  }),
  resolvedByUser: one(users, {
    fields: [packageUpgradeRequests.resolvedBy],
    references: [users.id],
  }),
}));

// ─── Limitations / Usage (Phase 17, read.md §12/§13) ─────────────────────────
//
// limit_definitions -> package_limits -> usage_records. Two new tables
// referencing `packages.id`, exactly as Phase 16's own write-up anticipated
// ("Phase 17 can add limit_definitions/package_limits... without touching
// anything this phase built"). `package_features` (ON/OFF entitlement) is
// left completely untouched.
//
// Unlimited representation: `packageLimits.limitValue` is a NULLABLE
// integer. NULL means "no cap" (unlimited), per the explicit Phase 1
// Research decision recorded in read.md ("NULL, not -1/999999, for
// unlimited") — a magic sentinel number is easy to misinterpret as a real
// value in a report/UI; NULL forces every reader to handle "unlimited" as
// its own branch rather than silently comparing against it.

export const limitDefinitions = pgTable(
  "limit_definitions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key", { length: 100 }).notNull().unique(),
    name: varchar("name", { length: 255 }).notNull(),
    description: text("description"),
    // e.g. "count", "MB", "requests" — a free label describing limitValue's
    // unit, not a closed enum (the Limitation Management Plan's example
    // list spans very different unit kinds: websites, pages, requests, MB).
    unit: varchar("unit", { length: 50 }).notNull().default("count"),
    // Default period for this metric; a package can override it per-package
    // via packageLimits.periodType below (e.g. most packages cap "Maximum
    // Reports" per month, but a promo package might cap it per week).
    periodType: limitPeriodEnum("period_type").notNull().default("month"),
    active: boolean("active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [index("limit_definitions_key_idx").on(t.key)]
);

export const packageLimits = pgTable(
  "package_limits",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    packageId: uuid("package_id")
      .notNull()
      .references(() => packages.id, { onDelete: "cascade" }),
    limitDefinitionId: uuid("limit_definition_id")
      .notNull()
      .references(() => limitDefinitions.id, { onDelete: "cascade" }),
    // NULL = unlimited for this package (see the file-level comment above).
    limitValue: integer("limit_value"),
    // Per-package override of the limit definition's default period; the
    // Quota gate always trusts this column (falling back to nothing — a
    // package_limits row always carries its own period, copied from the
    // definition's default at assignment time), so a change to a limit
    // definition's default period never silently reinterprets an
    // already-assigned package's window.
    periodType: limitPeriodEnum("period_type").notNull().default("month"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    unique("package_limits_package_limit_unique").on(t.packageId, t.limitDefinitionId),
    index("package_limits_package_id_idx").on(t.packageId),
  ]
);

// Usage tracking (§13): one row per user/metric/period-window, incremented
// in place by `recordUsage()` (upsert-per-period — see quota.ts's file
// comment for why insert-per-event was not chosen). `packageId` is nullable
// and purely informational/historical (which package the usage happened
// under, for reporting) — `checkQuota()` never joins through it to find the
// user's *current* package; it always re-reads `users.subscriptionPackageId`
// live, so a package change mid-period doesn't require rewriting usage rows.
export const usageRecords = pgTable(
  "usage_records",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    packageId: uuid("package_id").references(() => packages.id, { onDelete: "set null" }),
    metricKey: varchar("metric_key", { length: 100 }).notNull(),
    usageValue: integer("usage_value").default(0).notNull(),
    periodStart: timestamp("period_start").notNull(),
    periodEnd: timestamp("period_end").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("usage_records_user_metric_period_idx").on(t.userId, t.metricKey, t.periodStart),
    unique("usage_records_user_metric_period_unique").on(t.userId, t.metricKey, t.periodStart),
  ]
);

// ─── GSC: Google Search Console Integration (Phase 26) ───────────────────────
//
// A website may have at most one GSC connection (one Google account's OAuth
// tokens + one chosen verified property). `refreshTokenEncrypted` /
// `accessTokenEncrypted` are AES-256-GCM ciphertext (iv:authTag:ciphertext,
// base64, see `src/lib/gsc/crypto.ts`) — never plaintext, unlike the
// SHA-256 *hash* used for Phase 3's one-time password-reset tokens
// (`passwordResetTokens.tokenHash`): a hash can only be compared, never
// recovered, which is fine for a token the user re-supplies each time. A
// Google refresh token must be *decrypted and reused* on every sync, so
// hashing is not an option here — this is genuine symmetric encryption at
// rest, keyed from `GSC_TOKEN_ENCRYPTION_KEY` (see crypto.ts for key
// management notes).
//
// `propertyUrl` is nullable: OAuth can complete (tokens stored) before the
// user has picked which verified Search Console property this website maps
// to — the UI's second step (`GET/POST .../gsc/properties`) fills it in.

export const gscSyncStatusEnum = pgEnum("gsc_sync_status", [
  "never",
  "pending",
  "running",
  "completed",
  "failed",
]);

export const gscConnections = pgTable(
  "gsc_connections",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    connectedByUserId: uuid("connected_by_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // The verified GSC property (e.g. "https://example.com/" or
    // "sc-domain:example.com") this website is mapped to. Null until the
    // user completes the property-selection step.
    propertyUrl: text("property_url"),
    googleAccountEmail: varchar("google_account_email", { length: 255 }),
    scope: text("scope").notNull(),
    accessTokenEncrypted: text("access_token_encrypted").notNull(),
    accessTokenExpiresAt: timestamp("access_token_expires_at").notNull(),
    refreshTokenEncrypted: text("refresh_token_encrypted").notNull(),
    lastSyncStatus: gscSyncStatusEnum("last_sync_status").default("never").notNull(),
    lastSyncStartedAt: timestamp("last_sync_started_at"),
    lastSyncCompletedAt: timestamp("last_sync_completed_at"),
    lastSyncError: text("last_sync_error"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [uniqueIndex("gsc_connections_website_id_unique").on(t.websiteId)]
);

// One row per (website, sync batch, dimension type, dimension value) —
// dimensionType "query" holds the Search Analytics `dimensions: ["query"]`
// report, "page" holds the `dimensions: ["page"]` report, matching GSC's own
// "Queries" / "Pages" UI tabs and the master doc's named metrics (Queries,
// Pages, Clicks, Impressions, CTR, Position). Aggregated over the whole
// requested date range (no per-day breakdown row), same "one snapshot per
// triggered run" shape as `pagespeed_audits`. History is kept (not
// overwritten) via `syncId`; queries always read the most recent `syncId`.

export const gscDimensionEnum = pgEnum("gsc_dimension", ["query", "page"]);

export const gscMetrics = pgTable(
  "gsc_metrics",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    syncId: uuid("sync_id").notNull(),
    dimensionType: gscDimensionEnum("dimension_type").notNull(),
    dimensionValue: text("dimension_value").notNull(),
    clicks: integer("clicks").notNull(),
    impressions: integer("impressions").notNull(),
    ctr: real("ctr").notNull(),
    position: real("position").notNull(),
    dateRangeStart: varchar("date_range_start", { length: 10 }).notNull(),
    dateRangeEnd: varchar("date_range_end", { length: 10 }).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("gsc_metrics_website_id_idx").on(t.websiteId),
    index("gsc_metrics_sync_id_idx").on(t.syncId),
  ]
);

export const gscConnectionsRelations = relations(gscConnections, ({ one }) => ({
  website: one(websites, { fields: [gscConnections.websiteId], references: [websites.id] }),
  connectedByUser: one(users, { fields: [gscConnections.connectedByUserId], references: [users.id] }),
}));

export const gscMetricsRelations = relations(gscMetrics, ({ one }) => ({
  website: one(websites, { fields: [gscMetrics.websiteId], references: [websites.id] }),
}));

// ─── Phase 36: GA4 — Google Analytics 4 Integration ─────────────────────────
//
// Same trust model and OAuth mechanics as Phase 26's gsc_connections above
// (user-level OAuth against the SaaS's single shared Google Cloud OAuth
// client, encrypted-at-rest tokens, per-website unique connection) — see
// read.md's Phase 36 write-up for the full design rationale. Two deliberate
// differences from gsc_connections:
//   1. Tokens are encrypted with an INDEPENDENT key (`GA4_TOKEN_ENCRYPTION_KEY`,
//      see src/lib/ga4/crypto.ts) so rotating one integration's key never
//      affects the other.
//   2. There is no `ga4_metrics`-style history table (yet). The user
//      explicitly scoped this phase to "connection + live reporting" —
//      GA4 Data API `runReport` responses are fetched live on each report
//      view, not persisted. A metrics-history table is documented as
//      future work in read.md, not built here.
export const googleAnalyticsConnections = pgTable(
  "google_analytics_connections",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    googleAccountId: varchar("google_account_id", { length: 255 }),
    googleAccountEmail: varchar("google_account_email", { length: 255 }),
    scope: text("scope").notNull(),
    accessToken: text("access_token").notNull(), // AES-256-GCM ciphertext, see src/lib/ga4/crypto.ts
    refreshToken: text("refresh_token").notNull(), // AES-256-GCM ciphertext, see src/lib/ga4/crypto.ts
    tokenExpiresAt: timestamp("token_expires_at").notNull(),
    // GA4 property (e.g. "properties/123456789") the user selected as
    // matching this website. Null until the property-selection step
    // completes — OAuth can succeed before a property is chosen, same as
    // GSC's nullable propertyUrl.
    propertyId: text("property_id"),
    propertyName: text("property_name"),
    measurementId: varchar("measurement_id", { length: 64 }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [uniqueIndex("ga4_connections_website_id_unique").on(t.websiteId)]
);

export const googleAnalyticsConnectionsRelations = relations(googleAnalyticsConnections, ({ one }) => ({
  website: one(websites, { fields: [googleAnalyticsConnections.websiteId], references: [websites.id] }),
  user: one(users, { fields: [googleAnalyticsConnections.userId], references: [users.id] }),
}));

// ─── Phase 27: SERP — Manual Keyword & SERP Feature Tracking ────────────────
//
// SCOPING NOTE (see read.md's Phase 27 write-up and Key Decisions Log for the
// full reasoning): the master doc's Phase 27 section says "Manual keyword ...
// Top results, SERP features, PAA, Related searches" implemented "small-scale".
// This product deliberately does NOT scrape Google's SERPs itself — doing so
// would violate Google's Terms of Service and is exactly the kind of thing
// Section 3's excluded paid APIs (SerpAPI/DataForSEO) exist to abstract away.
// Instead this is a *manual, self-reported* keyword-tracking system: users
// log keywords they care about and manually record rank-check observations
// (position, SERP features present) over time. Where Phase 26's GSC
// connection is active, real Google-sourced position/click/impression data
// is cross-referenced live from `gsc_metrics` (see `src/lib/serp/queries.ts`)
// rather than requiring a manual entry — GSC data is always clearly labeled
// as "Source: Google Search Console", manual entries as "Source: Manual
// entry" (Section 79 #3 — never present self-reported data as measured).

export const trackedKeywords = pgTable(
  "tracked_keywords",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    addedByUserId: uuid("added_by_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    keyword: varchar("keyword", { length: 255 }).notNull(),
    // Optional: the page on this site this keyword is meant to rank for.
    targetUrl: text("target_url"),
    // Optional: ISO-ish country/locale code the user is tracking rank for
    // (purely descriptive metadata on a manual entry — this table never
    // performs a live geo-targeted search itself).
    country: varchar("country", { length: 10 }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("tracked_keywords_website_id_idx").on(t.websiteId),
    unique("tracked_keywords_website_keyword_country_unique").on(
      t.websiteId,
      t.keyword,
      t.country
    ),
  ]
);

// One row per manually-logged rank-check observation. `position` is
// nullable — a user may log "checked, not found in results I looked at"
// which is itself meaningful data, distinct from "never checked". Never
// auto-populated or fabricated (Section 79 #3): every row here was typed in
// by a human, and the UI must always label it "Manual entry" accordingly.
export const keywordRankChecks = pgTable(
  "keyword_rank_checks",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    trackedKeywordId: uuid("tracked_keyword_id")
      .notNull()
      .references(() => trackedKeywords.id, { onDelete: "cascade" }),
    checkedByUserId: uuid("checked_by_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    // Date the user performed the manual check (not necessarily "today" —
    // a user may be backfilling a historical observation).
    checkedDate: varchar("checked_date", { length: 10 }).notNull(),
    position: integer("position"),
    // Reasonable, non-exhaustive, extensible checklist — validated against
    // `SERP_FEATURE_OPTIONS` in `src/lib/serp/constants.ts` at the API layer,
    // stored as a plain jsonb string array (not a DB enum) precisely so the
    // list can grow without a migration.
    serpFeatures: jsonb("serp_features").$type<string[]>().default([]).notNull(),
    notes: text("notes"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("keyword_rank_checks_tracked_keyword_id_idx").on(t.trackedKeywordId),
    index("keyword_rank_checks_checked_date_idx").on(t.checkedDate),
  ]
);

export const trackedKeywordsRelations = relations(trackedKeywords, ({ one, many }) => ({
  website: one(websites, { fields: [trackedKeywords.websiteId], references: [websites.id] }),
  addedByUser: one(users, { fields: [trackedKeywords.addedByUserId], references: [users.id] }),
  rankChecks: many(keywordRankChecks),
}));

export const keywordRankChecksRelations = relations(keywordRankChecks, ({ one }) => ({
  trackedKeyword: one(trackedKeywords, {
    fields: [keywordRankChecks.trackedKeywordId],
    references: [trackedKeywords.id],
  }),
  checkedByUser: one(users, { fields: [keywordRankChecks.checkedByUserId], references: [users.id] }),
}));

// ─── Phase 29 — LLM/SLM/Local AI Integration ─────────────────────────────────
//
// Two new tables, deliberately separate from every deterministic table
// (`seo_issues`, `pages`, `schemas`, etc.) per master doc Section 79: AI
// output must never overwrite or be blended with a measured fact. Every row
// here IS the AI-inferred value — API responses additionally stamp
// `source: "ai_inferred"` (never "deterministic") so a client can never
// confuse the two even after JSON serialization. Same triggered-job /
// pending-running-completed-failed shape as `pagespeed_audits` (Phase 20) —
// AI calls have real latency, so this is an explicitly-triggered async job
// polled by the client, not an inline crawl step.

export const aiTaskStatusEnum = pgEnum("ai_task_status", ["pending", "running", "completed", "failed"]);

/**
 * Fills Phase 24's deliberately-`unassessed` GEO/AEO dimensions that are
 * genuinely LLM-shaped (Answerability, Semantic Completeness, Direct
 * Answers, Answer Completeness) once a real page-content read is available.
 * Evidence quality and Original Information are NOT here — see read.md's
 * Phase 29 write-up for why those stay `unassessed` even with an AI layer.
 */
export const aiPageAssessments = pgTable(
  "ai_page_assessments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    pageId: uuid("page_id")
      .notNull()
      .references(() => pages.id, { onDelete: "cascade" }),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    requestedByUserId: uuid("requested_by_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    status: aiTaskStatusEnum("status").default("pending").notNull(),
    provider: varchar("provider", { length: 50 }),
    model: varchar("model", { length: 100 }),
    promptVersion: varchar("prompt_version", { length: 20 }),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    error: text("error"),
    // Each dimension: { score: 0-100 | null, confidence: 0-1 | null, explanation: string }.
    // Always AI-inferred — never merged into `pages`/`seo_issues`.
    answerability: jsonb("answerability").$type<{ score: number | null; confidence: number | null; explanation: string }>(),
    semanticCompleteness: jsonb("semantic_completeness").$type<{ score: number | null; confidence: number | null; explanation: string }>(),
    directAnswers: jsonb("direct_answers").$type<{ score: number | null; confidence: number | null; explanation: string }>(),
    answerCompleteness: jsonb("answer_completeness").$type<{ score: number | null; confidence: number | null; explanation: string }>(),
    rawResponse: jsonb("raw_response"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("ai_page_assessments_page_id_idx").on(t.pageId),
    index("ai_page_assessments_website_id_idx").on(t.websiteId),
  ]
);

/**
 * Fills Phase 28's deliberately-deferred true topical/semantic content-gap
 * analysis: given the user's page content and a competitor's page content
 * (both already crawled by Phase 6/28's crawler), an LLM identifies
 * topics/subtopics/questions the competitor covers that the user's page
 * doesn't. Labeled "AI-Inferred Content Gap Analysis" everywhere it's
 * displayed — never blended with Phase 28's "Technical & Structural
 * Comparison", which stays 100% deterministic.
 */
export const aiContentGapAnalyses = pgTable(
  "ai_content_gap_analyses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    websiteId: uuid("website_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    competitorId: uuid("competitor_id")
      .notNull()
      .references(() => websites.id, { onDelete: "cascade" }),
    pageId: uuid("page_id").references(() => pages.id, { onDelete: "cascade" }),
    competitorPageId: uuid("competitor_page_id").references(() => pages.id, { onDelete: "cascade" }),
    requestedByUserId: uuid("requested_by_user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    status: aiTaskStatusEnum("status").default("pending").notNull(),
    provider: varchar("provider", { length: 50 }),
    model: varchar("model", { length: 100 }),
    promptVersion: varchar("prompt_version", { length: 20 }),
    startedAt: timestamp("started_at"),
    completedAt: timestamp("completed_at"),
    error: text("error"),
    yourUrl: text("your_url"),
    competitorUrl: text("competitor_url"),
    // Array of { topic, description, evidence }.
    gaps: jsonb("gaps").$type<{ topic: string; description: string; evidence: string }[]>(),
    summary: text("summary"),
    rawResponse: jsonb("raw_response"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("ai_content_gap_analyses_website_id_idx").on(t.websiteId),
    index("ai_content_gap_analyses_competitor_id_idx").on(t.competitorId),
  ]
);

export const aiPageAssessmentsRelations = relations(aiPageAssessments, ({ one }) => ({
  page: one(pages, { fields: [aiPageAssessments.pageId], references: [pages.id] }),
  website: one(websites, { fields: [aiPageAssessments.websiteId], references: [websites.id] }),
  requestedByUser: one(users, { fields: [aiPageAssessments.requestedByUserId], references: [users.id] }),
}));

export const aiContentGapAnalysesRelations = relations(aiContentGapAnalyses, ({ one }) => ({
  website: one(websites, { fields: [aiContentGapAnalyses.websiteId], references: [websites.id] }),
  competitor: one(websites, { fields: [aiContentGapAnalyses.competitorId], references: [websites.id] }),
  requestedByUser: one(users, { fields: [aiContentGapAnalyses.requestedByUserId], references: [users.id] }),
}));

// ─── Relations ───────────────────────────────────────────────────────────────

export const usersRelations = relations(users, ({ one, many }) => ({
  websites: many(websites),
  sessions: many(sessions),
  emailVerificationTokens: many(emailVerificationTokens),
  passwordResetTokens: many(passwordResetTokens),
  userRoles: many(userRoles),
  subscriptionPackage: one(packages, {
    fields: [users.subscriptionPackageId],
    references: [packages.id],
  }),
}));

export const featuresRelations = relations(features, ({ many }) => ({
  permissions: many(permissions),
  packageFeatures: many(packageFeatures),
}));

export const packagesRelations = relations(packages, ({ many }) => ({
  packageFeatures: many(packageFeatures),
  packageLimits: many(packageLimits),
  users: many(users),
}));

export const packageFeaturesRelations = relations(packageFeatures, ({ one }) => ({
  package: one(packages, { fields: [packageFeatures.packageId], references: [packages.id] }),
  feature: one(features, { fields: [packageFeatures.featureId], references: [features.id] }),
}));

export const limitDefinitionsRelations = relations(limitDefinitions, ({ many }) => ({
  packageLimits: many(packageLimits),
}));

export const packageLimitsRelations = relations(packageLimits, ({ one }) => ({
  package: one(packages, { fields: [packageLimits.packageId], references: [packages.id] }),
  limitDefinition: one(limitDefinitions, {
    fields: [packageLimits.limitDefinitionId],
    references: [limitDefinitions.id],
  }),
}));

export const usageRecordsRelations = relations(usageRecords, ({ one }) => ({
  user: one(users, { fields: [usageRecords.userId], references: [users.id] }),
  package: one(packages, { fields: [usageRecords.packageId], references: [packages.id] }),
}));

export const permissionsRelations = relations(permissions, ({ one, many }) => ({
  feature: one(features, { fields: [permissions.featureId], references: [features.id] }),
  rolePermissions: many(rolePermissions),
}));

export const rolesRelations = relations(roles, ({ many }) => ({
  rolePermissions: many(rolePermissions),
  userRoles: many(userRoles),
}));

export const rolePermissionsRelations = relations(rolePermissions, ({ one }) => ({
  role: one(roles, { fields: [rolePermissions.roleId], references: [roles.id] }),
  permission: one(permissions, {
    fields: [rolePermissions.permissionId],
    references: [permissions.id],
  }),
}));

export const userRolesRelations = relations(userRoles, ({ one }) => ({
  user: one(users, { fields: [userRoles.userId], references: [users.id] }),
  role: one(roles, { fields: [userRoles.roleId], references: [roles.id] }),
}));

export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, { fields: [sessions.userId], references: [users.id] }),
}));

export const emailVerificationTokensRelations = relations(
  emailVerificationTokens,
  ({ one }) => ({
    user: one(users, {
      fields: [emailVerificationTokens.userId],
      references: [users.id],
    }),
  })
);

export const passwordResetTokensRelations = relations(
  passwordResetTokens,
  ({ one }) => ({
    user: one(users, {
      fields: [passwordResetTokens.userId],
      references: [users.id],
    }),
  })
);

export const websitesRelations = relations(websites, ({ one, many }) => ({
  user: one(users, { fields: [websites.userId], references: [users.id] }),
  crawlRuns: many(crawlRuns),
  pages: many(pages),
}));

export const crawlRunsRelations = relations(crawlRuns, ({ one, many }) => ({
  website: one(websites, { fields: [crawlRuns.websiteId], references: [websites.id] }),
  pages: many(pages),
  llmsFiles: many(llmsFiles),
}));

export const llmsFilesRelations = relations(llmsFiles, ({ one }) => ({
  website: one(websites, { fields: [llmsFiles.websiteId], references: [websites.id] }),
  crawlRun: one(crawlRuns, { fields: [llmsFiles.crawlRunId], references: [crawlRuns.id] }),
}));

export const sitemapDocumentsRelations = relations(sitemapDocuments, ({ one }) => ({
  website: one(websites, { fields: [sitemapDocuments.websiteId], references: [websites.id] }),
  crawlRun: one(crawlRuns, { fields: [sitemapDocuments.crawlRunId], references: [crawlRuns.id] }),
}));

export const robotsFilesRelations = relations(robotsFiles, ({ one }) => ({
  website: one(websites, { fields: [robotsFiles.websiteId], references: [websites.id] }),
  crawlRun: one(crawlRuns, { fields: [robotsFiles.crawlRunId], references: [crawlRuns.id] }),
}));

export const pagesRelations = relations(pages, ({ one, many }) => ({
  website: one(websites, { fields: [pages.websiteId], references: [websites.id] }),
  crawlRun: one(crawlRuns, { fields: [pages.crawlRunId], references: [crawlRuns.id] }),
  metrics: many(pageMetrics),
  images: many(images),
  links: many(links),
  schemas: many(schemas),
  seoIssues: many(seoIssues),
}));

// ─── Installation State (Web Installer — Stage 1) ─────────────────────────────

/**
 * Web Installer — the durable, server-side installation lock.
 *
 * THE POINT OF THIS TABLE: `/install` can create the first SUPER_ADMIN, so
 * once installation is complete it must become genuinely unreachable. That
 * decision has to live somewhere an attacker cannot reach and an accident
 * cannot clear. It is therefore NOT a frontend flag, NOT a cookie, NOT
 * localStorage, and NOT only a file on disk:
 *
 *  - a cookie/localStorage flag is client state — clearing it "reopens" the
 *    installer, which is an authentication bypass, not a UX quirk;
 *  - a marker FILE is ephemeral in a container (every redeploy wipes it) and
 *    deletable by anything with write access to the project directory.
 *
 * The database is the only store in this deployment that is durable across
 * redeploys, shared by every app replica, and already the authority for who
 * is an administrator. So the database is authoritative here too: deleting
 * `.install-token`, clearing cookies, wiping localStorage, or redeploying the
 * container all leave `completed = true` exactly where it was.
 *
 * SINGLETON. Exactly one row, `id = 1`, enforced by a CHECK constraint in the
 * migration. There is one installation per database; a second row would be a
 * second, contradictory answer to "is this platform installed", which is the
 * kind of ambiguity a security lock must not have.
 */
export const installationState = pgTable("installation_state", {
  /** Always 1. CHECK-constrained in SQL so the singleton is a DB invariant. */
  id: integer("id").primaryKey(),
  completed: boolean("completed").default(false).notNull(),
  completedAt: timestamp("completed_at"),
  /**
   * The first SUPER_ADMIN this installer created. `set null` on delete so
   * removing that user can never cascade the LOCK away — the installation
   * stays complete even if the account that completed it is later deleted.
   */
  completedByUserId: uuid("completed_by_user_id").references(() => users.id, {
    onDelete: "set null",
  }),
  /**
   * Per-step progress, so a partially-finished installation is resumable and
   * every step is idempotent (re-running a completed step is a no-op rather
   * than a duplicate write). Shape is owned by `src/lib/install/state.ts`.
   * NEVER holds a secret value — only step ids, statuses and timestamps.
   */
  steps: jsonb("steps").$type<Record<string, { status: string; at: string }>>().default({}).notNull(),
  /**
   * Short SHA-256 prefix of the install token currently in use. Recorded for
   * operator correlation only ("the token in the logs is the token on disk"),
   * and it is NOT what verification compares against — verification reads the
   * token file, precisely so it keeps working while the database is the thing
   * being repaired. Non-reversible; not a credential.
   */
  tokenFingerprint: varchar("token_fingerprint", { length: 64 }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
