import type { RuleDefinition } from "./rules-registry";

/** Sitemap rules (Phase 12). All under the `technical` category, consistent with Phase 8's TECH_SITEMAP_MISSING. */
export const SITEMAP_RULES: RuleDefinition[] = [
  {
    ruleKey: "SITEMAP_HTTP_ERROR",
    category: "technical",
    severity: "high",
    title: "Sitemap returned an HTTP error",
    description: "A declared or discovered sitemap URL did not return a successful HTTP status.",
    recommendation: "Fix the sitemap URL or its hosting so it returns a 200 status.",
    impact: "Search engines cannot read a sitemap that fails to load.",
  },
  {
    ruleKey: "SITEMAP_INVALID_XML",
    category: "technical",
    severity: "high",
    title: "Sitemap contains invalid XML",
    description: "A sitemap document is not well-formed XML.",
    recommendation: "Fix the XML syntax error so the sitemap can be parsed.",
    impact: "Search engines cannot process a sitemap that fails to parse as XML.",
  },
  {
    ruleKey: "SITEMAP_DUPLICATE_URL",
    category: "technical",
    severity: "low",
    title: "Duplicate URL within sitemap",
    description: "The same URL appears more than once in a single sitemap document.",
    recommendation: "Remove duplicate <url> entries from the sitemap.",
    impact: "Duplicate entries add noise without adding value; sitemaps should list each URL once.",
  },
  {
    ruleKey: "SITEMAP_INVALID_URL",
    category: "technical",
    severity: "medium",
    title: "Invalid URL in sitemap",
    description: "A <loc> entry in the sitemap is not a valid absolute http/https URL.",
    recommendation: "Fix or remove the invalid URL entry.",
    impact: "Invalid URLs cannot be crawled or indexed and waste sitemap capacity.",
  },
  {
    ruleKey: "SITEMAP_HTTP_URL_ON_HTTPS_SITE",
    category: "technical",
    severity: "medium",
    title: "HTTP URL in sitemap on an HTTPS site",
    description: "The sitemap lists a plain http:// URL even though the site serves over HTTPS.",
    recommendation: "Update the sitemap to list the https:// version of the URL.",
    impact: "Mixed-protocol sitemap entries are inconsistent and may cause an unnecessary redirect hop.",
  },
  {
    ruleKey: "SITEMAP_TOO_MANY_URLS",
    category: "technical",
    severity: "medium",
    title: "Sitemap exceeds the 50,000 URL limit",
    description: "A single sitemap file lists more than 50,000 URLs, the protocol's per-file limit.",
    recommendation: "Split the sitemap into multiple files referenced by a sitemap index.",
    impact: "Sitemaps beyond the protocol limit may be rejected or partially ignored by search engines.",
  },
  {
    ruleKey: "SITEMAP_URL_MISSING_LASTMOD",
    category: "technical",
    severity: "info",
    title: "Sitemap URLs missing lastmod",
    description: "Some sitemap entries have no <lastmod> date.",
    recommendation: "Add accurate <lastmod> values so search engines can prioritize recrawling changed pages.",
    impact: "Without lastmod, search engines have less signal for how often to recheck a URL.",
  },
  {
    ruleKey: "SITEMAP_URL_BROKEN",
    category: "technical",
    severity: "high",
    title: "Sitemap lists a broken URL",
    description: "A URL listed in the sitemap returned a 4xx or 5xx status when crawled.",
    recommendation: "Remove the broken URL from the sitemap, or fix the page.",
    impact: "Broken URLs in a sitemap waste crawl budget and signal poor sitemap maintenance.",
  },
  {
    ruleKey: "SITEMAP_URL_NOT_INDEXABLE",
    category: "technical",
    severity: "medium",
    title: "Sitemap lists a non-indexable URL",
    description: "A URL listed in the sitemap is marked noindex.",
    recommendation: "Remove noindex URLs from the sitemap — sitemaps should only list indexable pages.",
    impact: "Listing non-indexable pages in a sitemap sends a contradictory signal to search engines.",
  },
  {
    ruleKey: "SITEMAP_URL_CANONICAL_MISMATCH",
    category: "technical",
    severity: "medium",
    title: "Sitemap URL differs from the page's canonical",
    description: "A URL listed in the sitemap is not the canonical URL for that page's content.",
    recommendation: "List the canonical URL in the sitemap, not an alternate/duplicate URL.",
    impact: "Sitemaps should reference canonical URLs; listing non-canonical URLs undermines the canonical signal.",
  },
];

export const SITEMAP_RULES_BY_KEY = new Map(SITEMAP_RULES.map((r) => [r.ruleKey, r]));
