import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth/current-user";
import { getWebsiteForUser, getCompetitorForUser } from "@/lib/websites/queries";
import { checkRateLimit } from "@/lib/auth";
import { startContentGapAnalysis, listGapAnalyses } from "@/lib/ai/gap-service";
import { AiUnavailableError } from "@/lib/ai/errors";

const idSchema = z.string().uuid();
const bodySchema = z.object({ pageId: z.string().uuid().optional(), competitorPageId: z.string().uuid().optional() });

/**
 * Phase 29 — fills Phase 28's deferred true topical/semantic content-gap
 * analysis. Deliberately a separate endpoint from
 * `/compare` (Phase 28's deterministic "Technical & Structural Comparison")
 * — never merged into that response, per Section 79's AI-vs-deterministic
 * separation.
 */
export async function POST(req: NextRequest, { params }: { params: Promise<{ id: string; competitorId: string }> }) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  }

  const { id, competitorId } = await params;
  if (!idSchema.safeParse(id).success || !idSchema.safeParse(competitorId).success) {
    return NextResponse.json({ error: "Competitor not found." }, { status: 404 });
  }

  const site = await getWebsiteForUser(user.id, id);
  if (!site) {
    return NextResponse.json({ error: "Website not found." }, { status: 404 });
  }
  const competitor = await getCompetitorForUser(user.id, site.id, competitorId);
  if (!competitor) {
    return NextResponse.json({ error: "Competitor not found." }, { status: 404 });
  }

  const rl = await checkRateLimit(user.id, "start_ai_content_gap");
  if (!rl.allowed) {
    return NextResponse.json({ error: "Too many content-gap analyses started recently. Please try again later." }, { status: 429 });
  }

  const raw = await req.json().catch(() => ({}));
  const parsed = bodySchema.safeParse(raw);
  const explicitPageIds = parsed.success ? parsed.data : undefined;

  try {
    const analysis = await startContentGapAnalysis(site.id, site.url, competitor.id, competitor.url, user.id, explicitPageIds);
    return NextResponse.json({ analysis: { ...analysis, source: "ai_inferred" } }, { status: 201 });
  } catch (err) {
    if (err instanceof AiUnavailableError) {
      return NextResponse.json({ error: err.message }, { status: 503 });
    }
    if (err instanceof Error) {
      return NextResponse.json({ error: err.message }, { status: 422 });
    }
    throw err;
  }
}

export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string; competitorId: string }> }) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  }

  const { id, competitorId } = await params;
  if (!idSchema.safeParse(id).success || !idSchema.safeParse(competitorId).success) {
    return NextResponse.json({ error: "Competitor not found." }, { status: 404 });
  }

  const site = await getWebsiteForUser(user.id, id);
  if (!site) {
    return NextResponse.json({ error: "Website not found." }, { status: 404 });
  }
  const competitor = await getCompetitorForUser(user.id, site.id, competitorId);
  if (!competitor) {
    return NextResponse.json({ error: "Competitor not found." }, { status: 404 });
  }

  const analyses = await listGapAnalyses(site.id, competitor.id);
  return NextResponse.json({
    analyses: analyses.map((a) => ({ ...a, source: "ai_inferred" })),
    label: "AI-Inferred Content Gap Analysis",
    disclaimer:
      "Generated by a locally-run language model comparing the live text of one of your pages against one of the competitor's pages. This is a semantic judgment, not a deterministic measurement — it is separate from, and never blended with, Phase 28's Technical & Structural Comparison. Absent an AI provider configuration, this feature reports unavailable rather than fabricating a result.",
  });
}
