import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { pages, websites } from "@/lib/db/schema";
import { and, eq } from "drizzle-orm";
import { getCurrentUser } from "@/lib/auth/current-user";
import { checkRateLimit } from "@/lib/auth";
import { startPageAssessment, listAssessmentsForPage, PageNotFoundError } from "@/lib/ai/assessment-service";
import { AiUnavailableError } from "@/lib/ai/errors";

const idSchema = z.string().uuid();

/**
 * Phase 29 — fills Phase 24's deferred Answerability / Semantic
 * Completeness / Direct Answers / Answer Completeness dimensions via the AI
 * gateway. Same POST-to-trigger / GET-to-poll shape as
 * `/api/websites/[id]/pagespeed`.
 */
async function assertOwnedPage(userId: string, pageId: string) {
  const [owned] = await db
    .select({ id: pages.id })
    .from(pages)
    .innerJoin(websites, eq(pages.websiteId, websites.id))
    .where(and(eq(pages.id, pageId), eq(websites.userId, userId)))
    .limit(1);
  return !!owned;
}

export async function POST(_req: NextRequest, { params }: { params: Promise<{ pageId: string }> }) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  }

  const { pageId } = await params;
  if (!idSchema.safeParse(pageId).success) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }

  if (!(await assertOwnedPage(user.id, pageId))) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }

  const rl = await checkRateLimit(user.id, "start_ai_assessment");
  if (!rl.allowed) {
    return NextResponse.json({ error: "Too many AI assessments started recently. Please try again later." }, { status: 429 });
  }

  try {
    const assessment = await startPageAssessment(pageId, user.id);
    return NextResponse.json({ assessment: { ...assessment, source: "ai_inferred" } }, { status: 201 });
  } catch (err) {
    if (err instanceof PageNotFoundError) {
      return NextResponse.json({ error: "Not found." }, { status: 404 });
    }
    if (err instanceof AiUnavailableError) {
      return NextResponse.json({ error: err.message }, { status: 503 });
    }
    throw err;
  }
}

export async function GET(_req: NextRequest, { params }: { params: Promise<{ pageId: string }> }) {
  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Not authenticated." }, { status: 401 });
  }

  const { pageId } = await params;
  if (!idSchema.safeParse(pageId).success) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }

  if (!(await assertOwnedPage(user.id, pageId))) {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }

  const assessments = await listAssessmentsForPage(pageId);
  return NextResponse.json({
    assessments: assessments.map((a) => ({ ...a, source: "ai_inferred" })),
    disclaimer:
      "AI-inferred assessments — generated by a locally-run language model reading this page's live text content, not a deterministic measurement. Never overwrites or is blended with this platform's rule-based SEO scores. Absent an AI provider configuration, this feature reports unavailable rather than fabricating a result.",
  });
}
