/**
 * Phase 37 — reads and writes for stored site-level file content.
 *
 * READS are what the Sitemap / Robots.txt / AI Search report pages call. They
 * are plain SELECTs over already-persisted rows: opening a report NEVER causes
 * a third-party file to be fetched. A file is fetched during a crawl, or when
 * a user explicitly adds one by hand — nowhere else.
 *
 * WHICH ROWS COUNT. A crawl writes one `discovered` set per run, so a report
 * shows the set belonging to the most recent COMPLETED run (matching what the
 * rest of the module report already reads from). `manual` rows carry no crawl
 * run, are not regenerated by crawling, and are always shown.
 *
 * NOTHING here invents a value. A website with no completed crawl and no
 * manual entries yields empty arrays, which every caller renders as "never
 * checked" — distinct from a stored row whose `found` is false, which is a
 * real, measured absence.
 */

import { and, desc, eq, isNull, or } from "drizzle-orm";
import type { AnyPgColumn } from "drizzle-orm/pg-core";

import { db } from "@/lib/db";
import { crawlRuns, llmsFiles, robotsFiles, sitemapDocuments } from "@/lib/db/schema";
import { parseSitemapXml } from "@/lib/crawler/sitemap-parser";
import { parseLlmsTxt } from "@/lib/crawler/llms-txt-parser";
import { fetchSiteFile, isFetchable, type SiteFileType } from "./fetch";

export type SiteFileSource = "discovered" | "manual";

/** One stored file, in the shape the report cards render. */
export interface SiteFileEntry {
  id: string;
  type: SiteFileType;
  url: string;
  source: SiteFileSource;
  found: boolean;
  httpStatus: number | null;
  rawContent: string | null;
  sizeBytes: number | null;
  truncated: boolean;
  fetchError: string | null;
  fetchedAt: Date;
  /** XML sitemaps only. */
  urlCount: number | null;
  /** XML sitemaps only. */
  isIndex: boolean | null;
  /** llms.txt only — the already-parsed title, surfaced from Phase 18's stored row. */
  title: string | null;
}

/** The most recent COMPLETED crawl run for a website, or null. */
async function latestCompletedRunId(websiteId: string): Promise<string | null> {
  const [run] = await db
    .select({ id: crawlRuns.id })
    .from(crawlRuns)
    .where(and(eq(crawlRuns.websiteId, websiteId), eq(crawlRuns.status, "completed")))
    .orderBy(desc(crawlRuns.completedAt), desc(crawlRuns.createdAt))
    .limit(1);
  return run?.id ?? null;
}

/**
 * Matches rows belonging to the latest completed run OR to no run at all
 * (manual). When there is no completed run, only manual rows match.
 */
function runScope(runId: string | null, column: AnyPgColumn) {
  return runId ? or(eq(column, runId), isNull(column)) : isNull(column);
}

export async function listSitemapDocuments(websiteId: string): Promise<SiteFileEntry[]> {
  const runId = await latestCompletedRunId(websiteId);
  const rows = await db
    .select()
    .from(sitemapDocuments)
    .where(and(eq(sitemapDocuments.websiteId, websiteId), runScope(runId, sitemapDocuments.crawlRunId)))
    .orderBy(desc(sitemapDocuments.fetchedAt));

  return rows.map((row) => ({
    id: row.id,
    type: row.kind === "html" ? ("sitemap_html" as const) : ("sitemap_xml" as const),
    url: row.url,
    source: row.source,
    found: row.found,
    httpStatus: row.httpStatus,
    rawContent: row.rawContent,
    sizeBytes: row.sizeBytes,
    truncated: row.truncated,
    fetchError: row.fetchError,
    fetchedAt: row.fetchedAt,
    urlCount: row.urlCount,
    isIndex: row.isIndex,
    title: null,
  }));
}

export async function listRobotsFiles(websiteId: string): Promise<SiteFileEntry[]> {
  const runId = await latestCompletedRunId(websiteId);
  const rows = await db
    .select()
    .from(robotsFiles)
    .where(and(eq(robotsFiles.websiteId, websiteId), runScope(runId, robotsFiles.crawlRunId)))
    .orderBy(desc(robotsFiles.fetchedAt));

  return rows.map((row) => ({
    id: row.id,
    type: "robots_txt" as const,
    url: row.url,
    source: row.source,
    found: row.found,
    httpStatus: row.httpStatus,
    rawContent: row.rawContent,
    sizeBytes: row.sizeBytes,
    truncated: row.truncated,
    fetchError: row.fetchError,
    fetchedAt: row.fetchedAt,
    urlCount: null,
    isIndex: null,
    title: null,
  }));
}

/**
 * llms.txt / llms-full.txt. Phase 18 has persisted the raw content of these
 * files since it was built — including `raw_content`, `title`, `summary` and
 * the parsed `sections` — but until Phase 37 NO screen in this product read
 * the table back, so every one of those bytes was invisible to the user. This
 * reader is the whole fix for that; nothing new is fetched.
 */
export async function listLlmsFiles(websiteId: string): Promise<(SiteFileEntry & { kind: "llms_txt" | "llms_full_txt"; summary: string | null })[]> {
  const runId = await latestCompletedRunId(websiteId);
  const rows = await db
    .select()
    .from(llmsFiles)
    .where(and(eq(llmsFiles.websiteId, websiteId), runScope(runId, llmsFiles.crawlRunId)))
    .orderBy(desc(llmsFiles.createdAt));

  return rows.map((row) => ({
    id: row.id,
    type: "llms_txt" as const,
    kind: row.kind,
    url: row.url,
    source: row.source,
    found: row.found,
    httpStatus: row.httpStatus,
    rawContent: row.rawContent,
    sizeBytes: row.sizeBytes,
    truncated: row.truncated,
    fetchError: row.fetchError,
    fetchedAt: row.createdAt,
    urlCount: null,
    isIndex: null,
    title: row.title,
    summary: row.summary,
  }));
}

// ─── Manual add / delete ─────────────────────────────────────────────────────

export interface ManualAddResult {
  entry: SiteFileEntry;
  /** Present when the file was reached but produced no body — surfaced verbatim to the user. */
  fetchError: string | null;
}

/**
 * Adds (or re-fetches) ONE user-supplied file URL.
 *
 * The URL has already been validated as http/https by the route's Zod schema;
 * the SSRF decision itself belongs to `safeFetch` inside `fetchSiteFile`, not
 * to a second allow/deny list here. An HTML sitemap is stored WITHOUT any
 * fetch at all — see `isFetchable`.
 */
export async function upsertManualSiteFile(
  websiteId: string,
  type: SiteFileType,
  url: string
): Promise<ManualAddResult> {
  const outcome = await fetchSiteFile(url, type);

  if (type === "sitemap_xml" || type === "sitemap_html") {
    const parsed = outcome.rawContent ? parseSitemapXml(outcome.rawContent) : null;
    const urlCount = parsed ? (parsed.kind === "sitemapindex" ? parsed.sitemapRefs.length : parsed.urls.length) : null;
    const [row] = await db
      .insert(sitemapDocuments)
      .values({
        websiteId,
        crawlRunId: null,
        url,
        kind: type === "sitemap_html" ? "html" : "xml",
        source: "manual",
        found: outcome.found,
        httpStatus: outcome.httpStatus,
        rawContent: outcome.rawContent,
        sizeBytes: outcome.sizeBytes,
        urlCount,
        isIndex: parsed ? parsed.kind === "sitemapindex" : null,
        truncated: outcome.truncated,
        fetchError: outcome.fetchError,
        fetchedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: [sitemapDocuments.websiteId, sitemapDocuments.url],
        targetWhere: eq(sitemapDocuments.source, "manual"),
        set: {
          kind: type === "sitemap_html" ? "html" : "xml",
          found: outcome.found,
          httpStatus: outcome.httpStatus,
          rawContent: outcome.rawContent,
          sizeBytes: outcome.sizeBytes,
          urlCount,
          isIndex: parsed ? parsed.kind === "sitemapindex" : null,
          truncated: outcome.truncated,
          fetchError: outcome.fetchError,
          fetchedAt: new Date(),
        },
      })
      .returning();

    return {
      entry: {
        id: row.id,
        type,
        url: row.url,
        source: "manual",
        found: row.found,
        httpStatus: row.httpStatus,
        rawContent: row.rawContent,
        sizeBytes: row.sizeBytes,
        truncated: row.truncated,
        fetchError: row.fetchError,
        fetchedAt: row.fetchedAt,
        urlCount: row.urlCount,
        isIndex: row.isIndex,
        title: null,
      },
      fetchError: outcome.fetchError,
    };
  }

  if (type === "robots_txt") {
    const [row] = await db
      .insert(robotsFiles)
      .values({
        websiteId,
        crawlRunId: null,
        url,
        source: "manual",
        found: outcome.found,
        httpStatus: outcome.httpStatus,
        rawContent: outcome.rawContent,
        sizeBytes: outcome.sizeBytes,
        truncated: outcome.truncated,
        fetchError: outcome.fetchError,
        fetchedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: [robotsFiles.websiteId, robotsFiles.url],
        targetWhere: eq(robotsFiles.source, "manual"),
        set: {
          found: outcome.found,
          httpStatus: outcome.httpStatus,
          rawContent: outcome.rawContent,
          sizeBytes: outcome.sizeBytes,
          truncated: outcome.truncated,
          fetchError: outcome.fetchError,
          fetchedAt: new Date(),
        },
      })
      .returning();

    return {
      entry: {
        id: row.id,
        type,
        url: row.url,
        source: "manual",
        found: row.found,
        httpStatus: row.httpStatus,
        rawContent: row.rawContent,
        sizeBytes: row.sizeBytes,
        truncated: row.truncated,
        fetchError: row.fetchError,
        fetchedAt: row.fetchedAt,
        urlCount: null,
        isIndex: null,
        title: null,
      },
      fetchError: outcome.fetchError,
    };
  }

  // llms.txt — reuses Phase 18's existing table and its existing parser, so a
  // manually-added file is described exactly like a crawl-discovered one.
  const parsed = outcome.rawContent ? parseLlmsTxt(outcome.rawContent) : null;
  const [row] = await db
    .insert(llmsFiles)
    .values({
      websiteId,
      crawlRunId: null,
      kind: "llms_txt",
      url,
      source: "manual",
      found: outcome.found,
      httpStatus: outcome.httpStatus,
      rawContent: outcome.rawContent,
      sizeBytes: outcome.sizeBytes,
      title: parsed?.title ?? null,
      summary: parsed?.summary ?? null,
      sections: parsed?.sections ?? null,
      truncated: outcome.truncated,
      fetchError: outcome.fetchError,
    })
    .onConflictDoUpdate({
      target: [llmsFiles.websiteId, llmsFiles.url],
      targetWhere: eq(llmsFiles.source, "manual"),
      set: {
        found: outcome.found,
        httpStatus: outcome.httpStatus,
        rawContent: outcome.rawContent,
        sizeBytes: outcome.sizeBytes,
        title: parsed?.title ?? null,
        summary: parsed?.summary ?? null,
        sections: parsed?.sections ?? null,
        truncated: outcome.truncated,
        fetchError: outcome.fetchError,
        createdAt: new Date(),
      },
    })
    .returning();

  return {
    entry: {
      id: row.id,
      type,
      url: row.url,
      source: "manual",
      found: row.found,
      httpStatus: row.httpStatus,
      rawContent: row.rawContent,
      sizeBytes: row.sizeBytes,
      truncated: row.truncated,
      fetchError: row.fetchError,
      fetchedAt: row.createdAt,
      urlCount: null,
      isIndex: null,
      title: row.title,
    },
    fetchError: outcome.fetchError,
  };
}

/**
 * Deletes ONE manually-added entry. The `source = 'manual'` predicate is part
 * of the WHERE clause, not a pre-check: a crawl-discovered row can never be
 * removed through this path, because the next crawl owns it.
 */
export async function deleteManualSiteFile(
  websiteId: string,
  type: SiteFileType,
  entryId: string
): Promise<boolean> {
  if (type === "sitemap_xml" || type === "sitemap_html") {
    const deleted = await db
      .delete(sitemapDocuments)
      .where(
        and(
          eq(sitemapDocuments.id, entryId),
          eq(sitemapDocuments.websiteId, websiteId),
          eq(sitemapDocuments.source, "manual")
        )
      )
      .returning({ id: sitemapDocuments.id });
    return deleted.length > 0;
  }

  if (type === "robots_txt") {
    const deleted = await db
      .delete(robotsFiles)
      .where(and(eq(robotsFiles.id, entryId), eq(robotsFiles.websiteId, websiteId), eq(robotsFiles.source, "manual")))
      .returning({ id: robotsFiles.id });
    return deleted.length > 0;
  }

  const deleted = await db
    .delete(llmsFiles)
    .where(and(eq(llmsFiles.id, entryId), eq(llmsFiles.websiteId, websiteId), eq(llmsFiles.source, "manual")))
    .returning({ id: llmsFiles.id });
  return deleted.length > 0;
}

export { isFetchable };
